version: "3.8"

services:
  mabede:
    container_name: mabede
    build:
      context: ./mabede
      dockerfile: ./production.dockerfile
      args:
        EXPOSED_PORT: 3000
        NODE_VERSION: 22.5
    ports:
      - 80:3000
    restart: always
    env_file:
      - ./env/database.env
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: mysql:9.0
    env_file:
      - ./env/database.env
    volumes:
      - mabede-database:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: 0s
      timeout: 2s
      retries: 10
      start_period: 0s

volumes:
  mabede-database:
