version: "3.8"

services:
  mabede:
    container_name: mabede
    build:
      context: ./mabede
    ports:
      - 80:3000
    depends_on:
      database:
        condition: service_completed_successfully

  database:
    container_name: database
    image: mysql:9.0
    env_file:
      - ./env/database.env
    volumes:
      - mabede-database:/database

volumes:
  mabede-database:
